AWSTemplateFormatVersion: 2010-09-09
Description: Creating IAM User Groups and assigning IAM Users to the User Groups via Cloudformation

Resources:

  IAMUserGroup1:
    Type: AWS::IAM::Group
    Properties: 
      GroupName: ProjectManager
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  IAMUserGroup2:
    Type: AWS::IAM::Group
    Properties: 
      GroupName: Developer
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/IAMUserChangePassword 
  
  IAMUser1:
    Type: AWS::IAM::User
    Properties:
      Groups: 
        - ProjectManager
      LoginProfile: 
        Password: P@33word
        PasswordResetRequired: True
      Tags: 
        - Key: Name
          Value: ProjectManagerG1
      UserName: CBAProjectManagerG1
  
  IAMUser2:
    Type: AWS::IAM::User
    Properties:
      Groups: 
        - Developer
      LoginProfile: 
        Password: P@33word
        PasswordResetRequired: True
      Tags: 
        - Key: Name
          Value: DeveloperG2
      UserName: CBADeveloperG2

  # myUserToGroupAddition:
  #   Type: AWS::IAM::UserToGroupAddition
  #   Properties:
  #     GroupName: ProjectManager # existing group name
  #     Users: # list of existing user names
  #       - IAMUser1
      # GroupName: Developer # existing group name
      # Users: # list of existing user names
      #   - IAMUser2
