AWSTemplateFormatVersion: 2010-09-09
Description: Creating IAM Users via Cloudformation

Resources:

  IAMUser1:
    Type: AWS::IAM::User
    Properties: 
      LoginProfile: 
        Password: P@33word
        PasswordResetRequired: True
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Tags: 
        - Key: Name
          Value: ProjectManager
      UserName: CBAProjectManager

  IAMUser2:
    Type: AWS::IAM::User
    Properties: 
      LoginProfile: 
        Password: P@33word
        PasswordResetRequired: True
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/IAMUserChangePassword
      Tags: 
        - Key: Name
          Value: Developer
      UserName: CBADeveloper

  IAMUser3:
    Type: AWS::IAM::User
    Properties: 
      LoginProfile: 
        Password: P@33word
        PasswordResetRequired: True
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/IAMUserChangePassword
      Tags: 
        - Key: Name
          Value: Intern
      UserName: CBAIntern