AWSTemplateFormatVersion: 2010-09-09
Description: Creating an S3 Bucket via Cloudformation

# test

Resources:
  S3:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private
      BucketName: cfjenkinsbucket12

  S3:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::AccountId}-${cfjenkinsbucket12}
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  ArtifactsBucketName:
    Description: 'S3 Bucket Name'
    Value: !Ref S3
    Export:
      Name: cfjenkinsbucket12
